### PR TITLE
Update Technical Vision to include datashader

### PR DESCRIPTION
**Pull request by jbednar**
Updated page as requested in https://github.com/bokeh/bokeh/issues/3859

### CODE REVIEW

**Comment by bryevdv** [comment]
LGTM

**Comment by bryevdv** [comment]
I went ahead and merged, I don't actually know how the site gets deployed. ping @birdsarah

**Comment by birdsarah** [comment]
cough: https://github.com/bokeh/bokehplots.com/blob/master/README.md#to-deploy

**Comment by birdsarah** [comment]
i'll do it next week :D

**Pull request merged**
